# Generated by Django 5.0.7 on 2024-08-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_rename_incomes_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
    ]
